routes/web.php
<?php


use Illuminate\Support\Facades\Auth;

Auth::routes();


    Route::get('docs','DocsController@auth');
    Route::get('docs/auth','DocsController@auth')->name('docs.auth');
    Route::get('docs/category','DocsController@category')->name('docs.category');
    Route::get('docs/question','DocsController@question')->name('docs.question');

    Route::get('pricing','PricingController@index')->name('pricing.index');

    Route::get('order/{id}','PaymentController@order')->name('payment.order');
    Route::post('payment/charge','PaymentController@charge')->name('payment.charge');
    Route::get('payment/{id}','PaymentController@index')->name('payment.index');






    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/home', 'HomeController@index');
    Route::resource('question','QuestionController');
    Route::resource('category','CategoryController');
    Route::resource('user','UserController');
    Route::resource('setting','SettingsController');
    Route::resource('plan','PlanController');
    Route::resource('plan_information','PlanInformationController');
    Route::get('question/create/{id}','QuestionController@create')->name('question.createInCategory');

app/Category.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = [
        'name','image_url'
    ];
    public function questions(){
        return $this->hasMany('App\Question');
    }

    public function getCreatedAtAttribute($date)
    {
        return Carbon::createFromFormat('Y-m-d H:i:s', $date)->format('d.m.Y H:i:s');
    }

    public function getUpdatedAtAttribute($date)
    {
        return Carbon::createFromFormat('Y-m-d H:i:s', $date)->format('d.m.Y H:i:s');
    }

}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Question;
use Illuminate\Http\Request;

class CategoryController extends Controller
{

    public function index()
    {
        $categories = Category::all();
        return view('category.index',['categories'=>$categories]);
    }


    public function create()
    {
        return view('category.create');
    }

    public function store(Request $request){
        $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'image' => ['required', 'image'],
            'image.*' => ['required', 'image'],
        ]);
        $image_url = '/storage/'.$request->file('image')->store('image');
        Category::create([
            'name' => $request->name,
            'image_url' => $image_url,
        ]);
        return redirect()->route('category.index');
    }

    public function show($id)
    {
        $questions = Question::where("parent_id",null)->where("category_id",$id)->get();

        return view('category.show',['questions'=>$questions]);
    }

    public function edit($id)
    {
        $category = Category::find($id);
        return view('category.edit',['category'=>$category]);
    }

    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'image' => ['required', 'image'],
            'image.*' => ['required', 'image'],
        ]);
        $image_url = '/storage/'.$request->file('image')->store('image');
        $category = Category::findOrFail($id);
        $category->name = $request->name;
        $category->image_url = $image_url;
        $category->save();
        return redirect()->route('category.index');
    }

    public function destroy($id)
    {
        $user = Category::find($id);
        $user->delete();
        if($user)
            echo 'ok';
        else
            echo'no';
    }
}

resources/views/category/create.blade.php
@extends('layouts.app')

@section('title')
    <title>Add Category</title>
@endsection

@section('content')
    <div class="container-fluid">
        @foreach ($errors->all() as $message) {
        {{$message}}
        @endforeach
        <form method="post" action="{{route('category.store')}}" class="slide" enctype="multipart/form-data">
            @csrf
            <div class="input-box">
                <span class="input-addon">
                    <i class="material-icons">subtitles</i>
                </span>
                <input name="name" required="" placeholder="Name">
            </div>

            <div class="input-box">
                <span class="input-addon">
                    <i class="material-icons">image</i>
                </span>
                <input name="image" type="file" id="image" class="hidden" role="image">
                <div class="file-input image-input" for="image">Upload</div>
                <div class="preview"><a class="image" href=""><img src="" title=""></a></div>
            </div>

            <div class="input-box submit">
                <button class="btn btn-success btn-iconed"><i class="material-icons">edit</i> Add Category</button>
            </div>


        </form>
    </div>
@endsection

@section('css')
    <link rel="stylesheet" href="{{asset('general/css/category.css')}}"/>
    <style>
        #spot-break{display: none;}
    </style>
@endsection

@section('js')
    <script src="{{asset('general/js/category.js')}}"></script>
@endsection

resources/views/category/edit.blade.php
@extends('layouts.app')

@section('title')
    <title>{{$category->name}} - Edit</title>
@endsection

@section('content')
    <div class="container-fluid">
        @foreach ($errors->all() as $message) {
        {{$message}}
        @endforeach
        <form method="post" action="{{route('category.update',['id'=>$category->id])}}" class="slide" enctype="multipart/form-data">
            @csrf
            @method('put')
            <div class="input-box">
                <span class="input-addon">
                    <i class="material-icons">subtitles</i>
                </span>
                <input name="name" required="" placeholder="Name" value="{{$category->name}}">
            </div>

            <div class="input-box">
                    <span class="input-addon">
                        <i class="material-icons">image</i>
                    </span>
                <input name="image" type="file" id="image" class="hidden" role="image">
                <div class="file-input image-input content-added" for="image">Upload</div>
                <div class="preview flex"><a class="image" href="{{$category->image_url}}"><img src="{{$category->image_url}}" title="{{$category->name}}"></a></div>
            </div>

            <div class="input-box submit">
                <button class="btn btn-success btn-iconed"><i class="material-icons">save</i> Save</button>
            </div>


        </form>
    </div>
@endsection

@section('css')
    <link rel="stylesheet" href="{{asset('general/css/category.css')}}"/>
    <style>
        #spot-break{display: none;}
    </style>
@endsection

@section('js')
    <script src="{{asset('general/js/category.js')}}"></script>
@endsection

resources/views/category/index.blade.php
@extends('layouts.app')

@section('title')
    <title>Categories</title>
@endsection

@section('content')
    <div class="container-fluid">
        <table class="data" id="category" border="1">
            <thead>
                <tr>
                    <td>Image</td>
                    <td>Name</td>
                    <td>Question Number</td>
                    <td>Options</td>
                </tr>
            </thead>
            <tbody>
            @foreach($categories as $category)
                @php
                    $count = \App\Question::where(["parent_id"=>null,"category_id"=>$category->id])->get()->count();
                @endphp
                <tr id="{{$category->id}}">
                    <td><a class="image" href="{{asset($category->image_url)}}"><img title="{{$category->name}}" src="{{asset($category->image_url)}}"/></a></td>
                    <td>{{$category->name}}</td>
                    <td>{{$count}}</td>
                    <td><a href="{{route('category.show',$category->id)}}"><button class="btn btn-secondary view"><i class="material-icons">remove_red_eye</i> View</button></a> <a href="{{route('category.edit',$category->id)}}"><button class="btn btn-primary edit"><i class="material-icons" data-target="#deleteModal">edit</i> Edit</button></a> <a href="#"><button class="btn btn-danger delete" data-target="#deleteModal" role="delete" route="{{route('category.destroy',['id'=>$category->id])}}"><i class="material-icons">delete</i> Delete</button></a></td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
@endsection

@section('js')
    <script src="{{asset('general/js/category.js')}}"></script>
@endsection

resources/views/category/show.blade.php
@extends('layouts.app')
@section('title')
    <title>Questions</title>
@endsection
@section('content')
    <div class="container-fluid">
        <table class="data" id="question" border="1">
            <thead>
            <tr>
                <td>Image</td>
                <td>Question</td>
                <td>Category</td>
                <td>Sub Questions</td>
                <td>Options</td>
            </tr>
            </thead>
            <tbody>
            @foreach($questions as $question)
                @php
                    $child_questions = \App\Question::where("parent_id",$question->id)->count();
                    $categoryName = \App\Category::find($question->category_id)->name;
                @endphp
                <tr id="{{$question->id}}">
                    <td><a class="image" href="{{asset($question->image_url)}}"><img title="{{$question->text}}" src="{{asset($question->image_url)}}"/></a></td>
                    <td>{{$question->text}}</td>
                    <td>{{$categoryName}}</td>
                    <td>{{$child_questions}}</td>
                    <td><a href="{{route('question.show',$question->id)}}"><button class="btn btn-secondary view"><i class="material-icons">remove_red_eye</i> View</button></a> <a href="{{route('question.edit',$question->id)}}"><button class="btn btn-primary edit"><i class="material-icons">edit</i> Edit</button></a> <a href="#"><button class="btn btn-danger delete" data-target="#deleteModal" role="delete" route="{{route('question.destroy',['id'=>$question->id])}}"><i class="material-icons">delete</i> Delete</button></a></td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
@endsection

@section('js')
    <script src="{{asset('general/js/question.js')}}"></script>
@endsection