routes/web.php
<?php


use Illuminate\Support\Facades\Auth;

Auth::routes();


    Route::get('docs','DocsController@auth');
    Route::get('docs/auth','DocsController@auth')->name('docs.auth');
    Route::get('docs/category','DocsController@category')->name('docs.category');
    Route::get('docs/question','DocsController@question')->name('docs.question');

    Route::get('pricing','PricingController@index')->name('pricing.index');

    Route::get('order/{id}','PaymentController@order')->name('payment.order');
    Route::post('payment/charge','PaymentController@charge')->name('payment.charge');
    Route::get('payment/{id}','PaymentController@index')->name('payment.index');






    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/home', 'HomeController@index');
    Route::resource('question','QuestionController');
    Route::resource('category','CategoryController');
    Route::resource('user','UserController');
    Route::resource('setting','SettingsController');
    Route::resource('plan','PlanController');
    Route::resource('plan_information','PlanInformationController');
    Route::get('question/create/{id}','QuestionController@create')->name('question.createInCategory');

app/User.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Tymon\JWTAuth\Contracts\JWTSubject;
use Laratrust\Traits\LaratrustUserTrait;

class User extends Authenticatable implements JWTSubject
{
    use LaratrustUserTrait;
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * Get the identifier that will be stored in the subject claim of the JWT.
     *
     * @return mixed
     */
    public function getJWTIdentifier()
    {
        return $this->getKey();
    }

    /**
     * Return a key value array, containing any custom claims to be added to the JWT.
     *
     * @return array
     */
    public function getJWTCustomClaims()
    {
        return [];
    }

    public function getCreatedAtAttribute($date)
    {
        return Carbon::createFromFormat('Y-m-d H:i:s', $date)->format('d.m.Y H:i:s');
    }

    public function getUpdatedAtAttribute($date)
    {
        return Carbon::createFromFormat('Y-m-d H:i:s', $date)->format('d.m.Y H:i:s');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;




class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */


    public function index()
    {
        $users = User::all();
        return view('user.index',['users'=>$users]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('user.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
            'password' => ['required', 'string', 'min:6', 'confirmed'],
            'role' => ['required', 'string']
        ]);

        $user = User::create([
            'name' => $request->name,
            'email' => $request->email,
            'password' => bcrypt($request->password)
        ]);

        $user->attachRole($request->role);
        $user->save();

        return redirect()->route('user.show',['id'=>$user->id]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::find($id);
        if($user) {
            checkPaymentTime($user->id);
            return view('user.show', ['user' => $user]);
        }else
            return redirect()->route('user.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::find($id);
        if($user)
            return view('user.edit',['user'=>$user]);
        else
            return redirect()->route('user.index');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255'],
            'role' => ['required', 'string']
        ]);

        $user = User::findOrFail($id);
        $user->name = $request->name;
        $user->email = $request->email;
        $user->detachRoles($user->roles);
        $user->attachRole($request->role);
        $user->save();
        return redirect()->route('user.show',['id'=>$id]);


    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::find($id);
        $user->delete();
        if($user)
            echo 'ok';
        else
            echo'no';
    }
}

resources/views/user/create.blade.php
@extends('layouts.app')

@section('title')
    <title>Add User</title>
@endsection

@section('content')
    <div class="container-fluid">
        @foreach ($errors->all() as $message) {
        {{$message}}
        @endforeach
        <form method="post" action="{{route('user.store')}}" class="slide">
            @csrf
            <div class="input-box">
                <span class="input-addon">
                    <i class="material-icons">person</i>
                </span>
                <input name="name" required="" placeholder="Name">
            </div>

            <div class="input-box">
                <span class="input-addon">
                    <i class="material-icons">alternate_email</i>
                </span>
                <input name="email" required="" placeholder="Email">
            </div>

            <div class="input-box">
                <span class="input-addon">
                    <i class="material-icons">lock</i>
                </span>
                <input name="password" required="" placeholder="Password">
            </div>

            <div class="input-box">
                <span class="input-addon">
                    <i class="material-icons">lock</i>
                </span>
                <input name="password_confirmation" required="" placeholder="Confirm Password">
            </div>

            <div class="input-box">
                <span class="input-addon">
                    <i class="material-icons">group_work</i>
                </span>
                <div class="dropdown-select">
                    <div class="select">
                        <span>Role</span>
                        <i class="fa fa-chevron-left"></i>
                    </div>
                    <input type="hidden" name="role" value="">
                    <ul class="dropdown-menu-select">
                        <li id="user">User</li>
                        <li id="editor">Editor</li>
                        <li id="admin">Admin</li>
                    </ul>
                </div>
            </div>

            <div class="input-box submit">
                <button class="btn btn-success btn-iconed"><i class="material-icons">save</i> Add User</button>
            </div>


        </form>
    </div>
@endsection

@section('css')
    <link rel="stylesheet" href="{{asset('general/css/user.css')}}"/>
    <style>
        #spot-break{display: none;}
    </style>
@endsection

@section('js')
    <script src="{{asset('general/js/user.js')}}"></script>
@endsection

resources/views/user/edit.blade.php
@extends('layouts.app')

@section('title')
    <title>{{$user->name}} - Edit</title>
@endsection

@section('content')
    <div class="container-fluid">
        @foreach ($errors->all() as $message) {
            {{$message}}
        @endforeach
        <form method="post" action="{{route('user.update',['id'=>$user->id])}}" class="slide">
            @csrf
            @method('put')
            <div class="input-box">
                <span class="input-addon">
                    <i class="material-icons">person</i>
                </span>
                <input name="name" required="" placeholder="Name" value="{{$user->name}}">
            </div>

            <div class="input-box">
                <span class="input-addon">
                    <i class="material-icons">alternate_email</i>
                </span>
                <input name="email" required="" placeholder="Email" value="{{$user->email}}">
            </div>

            <div class="input-box">
                <span class="input-addon">
                    <i class="material-icons">group_work</i>
                </span>
                <div class="dropdown-select">
                    <div class="select">
                        <span>{{$user->roles[0]->display_name}}</span>
                        <i class="fa fa-chevron-left"></i>
                    </div>
                    <input type="hidden" name="role" value="{{$user->roles[0]->name}}">
                    <ul class="dropdown-menu-select">
                        <li id="user" @if($user->roles[0]->name=='user') class="active" @endif>User</li>
                        <li id="editor" @if($user->roles[0]->name=='editor') class="active" @endif>Editor</li>
                        <li id="admin" @if($user->roles[0]->name=='admin') class="active" @endif>Admin</li>
                    </ul>
                </div>
            </div>

            <div class="input-box submit">
               <button class="btn btn-success btn-iconed"><i class="material-icons">save</i> Save</button>
            </div>


        </form>
    </div>
@endsection

@section('css')
    <link rel="stylesheet" href="{{asset('general/css/user.css')}}"/>
    <style>
        #spot-break{display: none;}
    </style>
@endsection

@section('js')
    <script src="{{asset('general/js/user.js')}}"></script>
@endsection

resources/views/user/index.blade.php
@extends('layouts.app')

@section('title')
    <title>Users</title>
@endsection

@section('content')
    <div class="container-fluid">
        <table class="data" id="user" border="1">
            <thead>
            <tr>
                <td>Name</td>
                <td>Email</td>
                <td>Role</td>
                <td>Options</td>
            </tr>
            </thead>
            <tbody>
            @foreach($users as $user)
                <tr id="{{$user->id}}">
                    <td>{{$user->name}}</td>
                    <td>{{$user->email}}</td>
                    <td>{{isset($user->roles[0])?$user->roles[0]->display_name:'User'}}</td>
                    <td>
                        <a href="{{route('user.show',$user->id)}}"><button class="btn btn-secondary view" role="view"><i class="material-icons" data-target="#deleteModal">remove_red_eye</i> View</button></a>
                        <a href="{{route('user.edit',$user->id)}}"><button class="btn btn-primary edit" role="edit"><i class="material-icons" data-target="#deleteModal">edit</i> Edit</button></a>
                        <a href="" onclick="return false;"><button class="btn btn-danger delete" route="{{route('user.destroy',['id'=>$user->id])}}" role="delete" data-target="#deleteModal"><i class="material-icons">delete</i> Delete</button></a>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
@endsection

@section('js')
    <script src="{{asset('general/js/user.js')}}"></script>
@endsection

resources/views/user/show.blade.php
@extends('layouts.app')

@section('title')
    <title>{{$user->name}}</title>
@endsection

@section('content')
    <div class="container-fluid">
        <div class="card">
            <div class="card-header relative">{{$user->name}}
                <div class="right-seat">
                    <a href="{{route('user.edit',$user->id)}}"><button class="btn btn-primary btn-iconed"><i class="material-icons">edit</i> Edit</button></a>
                    <a href="" onclick="return false;"><button class="btn btn-danger btn-iconed" id="{{$user->id}}" route="{{route('user.destroy',['id'=>$user->id])}}" role="delete"><i class="material-icons">delete</i> Delete</button></a>
                </div>
            </div>
            <div class="card-body">
                <div class="card-menu"> <div>Email</div> <div>{{$user->email}}</div> </div>
                <div class="card-menu"> <div>Role</div> <div>{{$user->roles[0]->display_name}}</div> </div>
                <div class="card-menu"> <div>Create Time</div> <div>{{$user->created_at}}</div> </div>
                <div class="card-menu"> <div>Update Time</div> <div>{{$user->updated_at}}</div> </div>

            </div>
        </div>
    </div>
@endsection