routes/web.php
<?php


use Illuminate\Support\Facades\Auth;

Auth::routes();


    Route::get('docs','DocsController@auth');
    Route::get('docs/auth','DocsController@auth')->name('docs.auth');
    Route::get('docs/category','DocsController@category')->name('docs.category');
    Route::get('docs/question','DocsController@question')->name('docs.question');

    Route::get('pricing','PricingController@index')->name('pricing.index');

    Route::get('order/{id}','PaymentController@order')->name('payment.order');
    Route::post('payment/charge','PaymentController@charge')->name('payment.charge');
    Route::get('payment/{id}','PaymentController@index')->name('payment.index');






    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/home', 'HomeController@index');
    Route::resource('question','QuestionController');
    Route::resource('category','CategoryController');
    Route::resource('user','UserController');
    Route::resource('setting','SettingsController');
    Route::resource('plan','PlanController');
    Route::resource('plan_information','PlanInformationController');
    Route::get('question/create/{id}','QuestionController@create')->name('question.createInCategory');

app/PlanInformation.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class PlanInformation extends Model
{
    //
}

app/Http/Controllers/PlanInformationController.php
<?php

namespace App\Http\Controllers;

use App\Plan;
use App\PlanInformation;
use Illuminate\Http\Request;

class PlanInformationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $infos = PlanInformation::all();
        return view('plan_information.index',['infos'=>$infos]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('plan_information.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => ['required','string']
        ]);

        $info = new PlanInformation;
        $info->name = $request->name;
        $info->save();

        return redirect()->route('plan_information.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $info = PlanInformation::find($id);
        return view('plan_information.edit',['info'=>$info]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => ['required','string']
        ]);

        $info = PlanInformation::find($id);
        $info->name = $request->name;
        $info->save();

        return redirect()->route('plan_information.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $info = PlanInformation::find($id);
        $info->delete();
        echo $info?'ok':'no';
    }
}

resources/views/plan_information/create.blade.php
@extends('layouts.app')

@section('title')
    <title>Add Plan Information</title>
@endsection

@section('content')
    <div class="container-fluid">
        @foreach ($errors->all() as $message) {
        {{$message}}
        @endforeach
        <form method="post" action="{{route('plan_information.store')}}" class="slide">
            @csrf
            <div class="input-box">
                <span class="input-addon">
                    <i class="material-icons">subtitles</i>
                </span>
                <input name="name" required="" placeholder="Name">
            </div>

            <div class="input-box submit">
                <button class="btn btn-success btn-iconed"><i class="material-icons">save</i> Add Plan Information</button>
            </div>


        </form>
    </div>
@endsection

@section('css')
    <style>
        #spot-break{display: none;}
    </style>
@endsection

resources/views/plan_information/edit.blade.php
@extends('layouts.app')

@section('title')
    <title>Edit Plan Information - {{$info->name}}</title>
@endsection

@section('content')
    <div class="container-fluid">
        @foreach ($errors->all() as $message) {
        {{$message}}
        @endforeach
        <form method="post" action="{{route('plan_information.update',['id'=>$info->id])}}" class="slide">
            @csrf
            @method('put')
            <div class="input-box">
                <span class="input-addon">
                    <i class="material-icons">subtitles</i>
                </span>
                <input name="name" required="" placeholder="Name" value="{{$info->name}}">
            </div>

            <div class="input-box submit">
                <button class="btn btn-success btn-iconed"><i class="material-icons">save</i> Edit Plan Information</button>
            </div>


        </form>
    </div>
@endsection

resources/views/plan_information/index.blade.php
@extends('layouts.app')
@section('title')
    <title>Plans</title>
@endsection
@section('content')
    <div class="container-fluid">
        <table class="data" id="question" border="1">
            <thead>
            <tr>
                <td>Name</td>
                <td>Options</td>
            </tr>
            </thead>
            <tbody>
            @foreach($infos as $info)
                <tr id="{{$info->id}}">
                    <td>{{$info->name}}</td>
                    <td><a href="{{route('plan_information.edit',$info->id)}}"><button class="btn btn-primary edit"><i class="material-icons">edit</i> Edit</button></a> <a href="#"><button class="btn btn-danger delete" data-target="#deleteModal" role="delete" route="{{route('plan_information.destroy',['id'=>$info->id])}}"><i class="material-icons">delete</i> Delete</button></a></td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
@endsection